"""Constants for the Public Transport Victoria integration."""

CONF_DIRECTION = "direction"
CONF_DIRECTION_NAME = "direction_name"
CONF_ROUTE = "route"
CONF_ROUTE_NAME = "route_name"
CONF_ROUTE_TYPE = "route_type"
CONF_ROUTE_TYPE_NAME = "route_type_name"
CONF_STOP = "stop"
CONF_STOP_NAME = "stop_name"
CONF_DESTINATION_STOP ="destination_stop"
CONF_DESTINATION_STOP_NAME ="destination_stop_name"
DOMAIN = "public_transport_victoria"
ATTRIBUTION = "Licensed from Public Transport Victoria under a Creative Commons Attribution 4.0 International Licence"
